# Generated by Django 4.1.7 on 2023-03-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationVoitures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='MainImage',
            field=models.CharField(default='default.jpg', max_length=100),
        ),
    ]
