# Generated by Django 4.1.7 on 2023-03-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationVoitures', '0002_voiture_mainimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='voiture',
            name='BoiteVitesse',
            field=models.CharField(default='Automatique', max_length=100),
        ),
        migrations.AddField(
            model_name='voiture',
            name='Couleur',
            field=models.CharField(default='Noir', max_length=100),
        ),
        migrations.AddField(
            model_name='voiture',
            name='Kilometrage',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='voiture',
            name='NombrePlaces',
            field=models.IntegerField(default=5, max_length=100),
        ),
        migrations.AddField(
            model_name='voiture',
            name='PrixDeLocation',
            field=models.FloatField(default=300),
        ),
    ]
