# Generated by Django 4.1.7 on 2023-03-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationVoitures', '0003_remove_voiture_pub_date_voiture_boitevitesse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CinOrPassportId', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=100)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=250)),
                ('Telephone', models.CharField(max_length=30)),
                ('Adresse', models.CharField(max_length=200)),
            ],
        ),
    ]
