# Generated by Django 4.1.7 on 2023-04-01 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LocationVoitures', '0006_message_lu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('prix_total', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationVoitures.client')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationVoitures.voiture')),
            ],
        ),
    ]
