# Generated by Django 4.1.7 on 2023-04-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LocationVoitures', '0007_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LocationVoitures.client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='voiture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LocationVoitures.voiture'),
        ),
    ]
