# Generated by Django 4.1.7 on 2023-04-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationVoitures', '0008_alter_reservation_client_alter_reservation_voiture'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='Disponible',
            field=models.BooleanField(default=True),
        ),
    ]
