# Generated by Django 4.1.7 on 2023-04-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LocationVoitures', '0009_voiture_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationVoitures.client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationVoitures.voiture'),
        ),
    ]
