# Generated by Django 4.1.7 on 2023-04-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationVoitures', '0010_alter_reservation_client_alter_reservation_voiture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='Kilometrage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='NombrePlaces',
            field=models.IntegerField(default=5),
        ),
    ]
